# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eh89FzFJlXtAMaA02R1hZG9Lw81FMb-3
"""

# import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# load  train and test data
df_test=pd.read_csv('/content/test.csv')
df_train=pd.read_csv('/content/train.csv')

# discover datasets
df_test.head(10)
df_train.head(10)

# data cleaning
df_train.isnull().sum()
df_test.isnull().sum()

# check duplicated val
print(df_test.duplicated().any())
print(df_train.duplicated().any())

# data EDA
# Categorical Feature Distributions

# POSTED_BY distribution
sns.countplot(x='POSTED_BY', data=df_train, palette="Set2")
plt.title("Distribution of Properties by POSTED_BY")
plt.show()

# UNDER_CONSTRUCTION
sns.countplot(x='UNDER_CONSTRUCTION', data=df_train, palette="Set3")
plt.title("Under Construction vs Not")
plt.show()

# READY_TO_MOVE
df_train['READY_TO_MOVE'].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, colors=sns.color_palette("pastel"))
plt.title("Ready to Move Status")
plt.ylabel("")
plt.show()

# RESALE
sns.countplot(x='RESALE', data=df_train, palette="coolwarm")
plt.title("Resale vs New Property")
plt.show()

# BHK_OR_RK
sns.countplot(x='BHK_OR_RK', data=df_train, palette="muted")
plt.title("BHK vs RK Distribution")
plt.show()

"""*  POSTED_BY distribution
Most properties are listed by Dealers, followed by Owners and Builders.
This indicates that dealers dominate the property market listings in this dataset, while builders contribute the least.
Such information can help understand the source of listings and potential market trends.

* UNDER_CONSTRUCTION
Most properties in the dataset are not under construction (count = 0 is the highest).
This suggests that the majority of listed properties are either ready or in a completed state, which could be important for buyers looking for immediately available properties.

*   pie plot

Around 82% of properties are ready to move, while the remaining 18% are not.
This indicates that the market is dominated by completed properties, which can be more attractive to buyers seeking immediate possession.
Visualizing it as a pie chart highlights the clear majority of ready-to-move listings.

*   RESALE
Most properties in the dataset are resale properties (value = 1 has the highest count).
This suggests that previously owned properties dominate the listings compared to new properties, which could be useful for understanding market trends and buyer preferences.

*   BHK_OR_RK
Most properties in the dataset are BHK units, compared to RK units.
This indicates that standard multi-room apartments dominate the market, which can help understand property types preferred by buyers and listed by sellers.

"""

# Numerical Feature Distributions
# Distribution of Square Feet
sns.histplot(df_train['SQUARE_FT'], bins=50, kde=True, color="skyblue")
plt.title("Distribution of Square Feet")
plt.show()

# Distribution of Target Price
sns.histplot(df_train['TARGET(PRICE_IN_LACS)'], bins=50, kde=True, color="green")
plt.title("Distribution of Price (in Lacs)")
plt.show()

"""*   Distribution of Square Feet
The distribution of property sizes shows that most properties have a smaller area, around 35,000 sq.ft, while a few properties are much larger, reaching up to 250,000 sq.ft.
This indicates a right-skewed distribution with a few extremely large properties acting as outliers.
Such insights are useful for understanding typical property sizes in the market.

*   Distribution of Target Price
The price distribution shows that most properties are priced on the lower end, while a few properties have very high prices, creating a right-skewed distribution.
This indicates the presence of high-value outliers in the market, which is important to consider when analyzing property trends or predicting prices.

"""

# Train vs Test Comparison
# POSTED_BY comparison
fig, axes = plt.subplots(1,2, figsize=(12,5))
sns.countplot(x='POSTED_BY', data=df_train, ax=axes[0], palette="Set2")
axes[0].set_title("Train Data")
sns.countplot(x='POSTED_BY', data=df_test, ax=axes[1], palette="Set3")
axes[1].set_title("Test Data")
plt.show()

# SQUARE_FT comparison
plt.figure(figsize=(10,5))
sns.kdeplot(df_train['SQUARE_FT'], label="Train", shade=True)
sns.kdeplot(df_test['SQUARE_FT'], label="Test", shade=True)
plt.title("Square Feet Distribution: Train vs Test")
plt.legend()
plt.show()

"""*   Train vs Test Comparison - POSTED_BY comparison
Both train and test datasets show a very similar distribution for POSTED_BY.
In both sets, Dealers list the most properties, followed by Owners and then Builders.
This indicates that the train and test sets are consistent in terms of property listing sources, which is important for maintaining data reliability when analyzing or modeling property trends.

*  SQUARE_FT comparison
The SQUARE_FT distributions in train and test datasets are similar but slightly different in density.
The test set has a higher peak density (~2) compared to the train set (~1.23), indicating that more properties in the test set cluster around a common size.
Overall, both datasets cover a similar range of property sizes, which shows good consistency between train and test for this numerical feature.


"""